/*
 * Copyright (C) 2024 Whitehole Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package whitehole.editor;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import whitehole.MainFrame;
import whitehole.Whitehole;
import whitehole.io.FileBase;
import whitehole.io.RarcFile;
import whitehole.math.Vec3f;
import whitehole.smg.Bcsv;
import whitehole.smg.Bcsv.Entry;
import whitehole.smg.GalaxyArchive;
import whitehole.smg.StageArchive;
import whitehole.smg.StageHelper;
import whitehole.smg.object.LevelObj;
import whitehole.smg.object.StartObj;

public class CreateGalaxyForm extends javax.swing.JFrame {
    private final boolean isGalaxyMode;
    /**
     * Creates new form CreateGalaxyForm
     * @param isGalaxy Whether it is creating a new galaxy or a new zone
     */
    public CreateGalaxyForm(boolean isGalaxy) {
        isGalaxyMode = isGalaxy;
        initComponents();
    }
    
    private void showMapError(String error) {
        JOptionPane.showMessageDialog(rootPane, "Failed to create map file.\n" + error, Whitehole.NAME, JOptionPane.ERROR_MESSAGE);
    }
    
    private void showScenarioError(String error) {
        JOptionPane.showMessageDialog(rootPane, "Failed to create scenario file.\n" + error, Whitehole.NAME, JOptionPane.ERROR_MESSAGE);
    }
    
    private ArrayList<String> getLayers() {
        JCheckBox[] layers = {
            chkLayerA, chkLayerB, chkLayerC, chkLayerD,
            chkLayerE, chkLayerF, chkLayerG, chkLayerH, 
            chkLayerI, chkLayerJ, chkLayerK, chkLayerL, 
            chkLayerM, chkLayerN, chkLayerO, chkLayerP
        };
        String layerStr = "ABCDEFGHIJKLMNOP";
        
        ArrayList<String> layersToAdd = new ArrayList<>();
        layersToAdd.add("Common");
        int layerNum = 0;
        for (JCheckBox layer : layers) {
            if (layer.isSelected())
                layersToAdd.add("Layer" + layerStr.charAt(layerNum));
            layerNum++;
        }
        return layersToAdd;
    }
    
    private void createZone(String newFileName) {
        try {
            StageHelper.createZone(newFileName, getLayers());
        } catch (IOException ex) {
            showMapError(ex.toString());
        }
    }
    
    private void createGalaxy(String galaxyName) {
        ArrayList<String> zones = new ArrayList<>();
        zones.add(galaxyName);
        try {
            StageHelper.createGalaxy(galaxyName, zones, getLayers());
        } catch (IOException ex) {
            showScenarioError(ex.toString());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblGalaxyName = new javax.swing.JLabel();
        txtGalaxyName = new javax.swing.JTextField();
        lblLayers = new javax.swing.JLabel();
        pnlLayers = new javax.swing.JPanel();
        chkLayerA = new javax.swing.JCheckBox();
        chkLayerB = new javax.swing.JCheckBox();
        chkLayerC = new javax.swing.JCheckBox();
        chkLayerD = new javax.swing.JCheckBox();
        chkLayerE = new javax.swing.JCheckBox();
        chkLayerF = new javax.swing.JCheckBox();
        chkLayerG = new javax.swing.JCheckBox();
        chkLayerH = new javax.swing.JCheckBox();
        chkLayerI = new javax.swing.JCheckBox();
        chkLayerJ = new javax.swing.JCheckBox();
        chkLayerK = new javax.swing.JCheckBox();
        chkLayerL = new javax.swing.JCheckBox();
        chkLayerM = new javax.swing.JCheckBox();
        chkLayerN = new javax.swing.JCheckBox();
        chkLayerO = new javax.swing.JCheckBox();
        chkLayerP = new javax.swing.JCheckBox();
        btnCreateGalaxy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Whitehole.NAME + (isGalaxyMode ? " -- Create a Galaxy" : " -- Create a Zone"));

        lblGalaxyName.setText(isGalaxyMode ? "Galaxy Name" : "Zone Name");

        txtGalaxyName.setText(isGalaxyMode ? "NewGalaxy" : "NewZone");

        lblLayers.setText("Layers to Create");

        pnlLayers.setLayout(new java.awt.GridBagLayout());

        chkLayerA.setSelected(true);
        chkLayerA.setText("Layer A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerA, gridBagConstraints);

        chkLayerB.setText("Layer B");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerB, gridBagConstraints);

        chkLayerC.setText("Layer C");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerC, gridBagConstraints);

        chkLayerD.setText("Layer D");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerD, gridBagConstraints);

        chkLayerE.setText("Layer E");
        chkLayerE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLayerEActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerE, gridBagConstraints);

        chkLayerF.setText("Layer F");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerF, gridBagConstraints);

        chkLayerG.setText("Layer G");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerG, gridBagConstraints);

        chkLayerH.setText("Layer H");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerH, gridBagConstraints);

        chkLayerI.setText("Layer I");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerI, gridBagConstraints);

        chkLayerJ.setText("Layer J");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerJ, gridBagConstraints);

        chkLayerK.setText("Layer K");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerK, gridBagConstraints);

        chkLayerL.setText("Layer L");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerL, gridBagConstraints);

        chkLayerM.setText("Layer M");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerM, gridBagConstraints);

        chkLayerN.setText("Layer N");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerN, gridBagConstraints);

        chkLayerO.setText("Layer O");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerO, gridBagConstraints);

        chkLayerP.setText("Layer P");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLayers.add(chkLayerP, gridBagConstraints);

        btnCreateGalaxy.setText(isGalaxyMode ? "Create Galaxy" : "Create Zone");
        btnCreateGalaxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateGalaxyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGalaxyName)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtGalaxyName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLayers, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlLayers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                        .addContainerGap(39, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateGalaxy)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGalaxyName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGalaxyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLayers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateGalaxy)
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkLayerEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLayerEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLayerEActionPerformed

    private void btnCreateGalaxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateGalaxyActionPerformed
        if (isGalaxyMode)
            createGalaxy(txtGalaxyName.getText());
        else
            createZone(txtGalaxyName.getText());
    }//GEN-LAST:event_btnCreateGalaxyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateGalaxy;
    private javax.swing.JCheckBox chkLayerA;
    private javax.swing.JCheckBox chkLayerB;
    private javax.swing.JCheckBox chkLayerC;
    private javax.swing.JCheckBox chkLayerD;
    private javax.swing.JCheckBox chkLayerE;
    private javax.swing.JCheckBox chkLayerF;
    private javax.swing.JCheckBox chkLayerG;
    private javax.swing.JCheckBox chkLayerH;
    private javax.swing.JCheckBox chkLayerI;
    private javax.swing.JCheckBox chkLayerJ;
    private javax.swing.JCheckBox chkLayerK;
    private javax.swing.JCheckBox chkLayerL;
    private javax.swing.JCheckBox chkLayerM;
    private javax.swing.JCheckBox chkLayerN;
    private javax.swing.JCheckBox chkLayerO;
    private javax.swing.JCheckBox chkLayerP;
    private javax.swing.JLabel lblGalaxyName;
    private javax.swing.JLabel lblLayers;
    private javax.swing.JPanel pnlLayers;
    private javax.swing.JTextField txtGalaxyName;
    // End of variables declaration//GEN-END:variables
}
